version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "Placeholder: github action will replace this"
        LoadBalancerInfo:
          ContainerName: "HelloappContainer"
          ContainerPort: 8080
